border_color_frm = 'SpringGreen3'
border_width_frm = 3
corner_radius_frm = 10
font_arg = ('Adobe Garamond Pro Bold', 15)
padx_frm = 9
pady_frm = 16
ipadx_frm = 20
ipady_frm = 5
padx_lbl = 20
pady_lbl = 5
padx_btn = 20
pady_btn = 5